/**
 * Commercial Executive Scenario Pack — acceptance criteria.
 */

import type { ScenarioPack } from "@/scenarios/framework/types";

export const COMMERCIAL_SCENARIO_PACK: ScenarioPack = {
  id: "pack-commercial-executive",
  name: "Commercial Executive Scenario Pack",
  profileId: "commercial_executive",
  requiredProviders: ["microsoft365", "salesforce"],
  description:
    "Executive questions Commercial leaders must have answered every morning.",
  scenarios: [
    {
      id: "com-overnight-changes",
      name: "Overnight changes",
      profileId: "commercial_executive",
      businessQuestion: "What changed overnight?",
      expectedInsight:
        "Overnight commercial delta: pipeline, accounts, forecast, renewals.",
      evidenceSources: ["microsoft365", "salesforce", "knowledge_graph"],
      requiredProviders: ["microsoft365", "salesforce"],
      successCriteria: [
        "Overnight commercial delta present",
        "Material changes prioritised",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Commercial day starts with clarity, not CRM browsing",
      reviewFrequency: "daily",
      expectedEvidence: ["Pipeline movement", "Meeting changes", "Account alerts"],
      expectedRecommendation: "Review overnight commercial changes first",
      expectedExecutiveAction: "Acknowledge material overnight pipeline/account shifts",
    },
    {
      id: "com-opportunities-intervention",
      name: "Opportunities needing intervention",
      profileId: "commercial_executive",
      businessQuestion: "Which opportunities require executive intervention?",
      expectedInsight: "Deals stalled or at risk that need executive sponsorship",
      evidenceSources: ["salesforce", "microsoft365"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "Intervention opportunities listed when commercial context available",
        "Why intervention is needed is clear",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Executive time unblocks revenue-critical deals",
      reviewFrequency: "daily",
      expectedEvidence: ["Stalled opportunities", "Close date risk", "Missing next step"],
      expectedRecommendation: "Intervene on the highest-value at-risk opportunity",
      expectedExecutiveAction: "Join or schedule an executive sponsor call",
    },
    {
      id: "com-strategic-accounts",
      name: "Strategic accounts weakening",
      profileId: "commercial_executive",
      businessQuestion: "Which strategic accounts are weakening?",
      expectedInsight: "Strategic accounts with weakening engagement or health",
      evidenceSources: ["salesforce", "microsoft365", "knowledge_graph"],
      requiredProviders: ["microsoft365", "salesforce"],
      successCriteria: [
        "Weakening strategic accounts identified",
        "Signal of weakening explained",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Protect strategic revenue relationships",
      reviewFrequency: "weekly",
      expectedEvidence: ["Account health", "Engagement drop", "Open risks"],
      expectedRecommendation: "Engage the weakening strategic account this week",
      expectedExecutiveAction: "Personal outreach to account executive sponsor",
    },
    {
      id: "com-forecast-confidence",
      name: "Forecast confidence change",
      profileId: "commercial_executive",
      businessQuestion: "How has forecast confidence changed?",
      expectedInsight: "Direction and drivers of forecast confidence movement",
      evidenceSources: ["salesforce"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "Forecast confidence signal present",
        "Change direction explained",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Leadership trusts the forecast narrative",
      reviewFrequency: "weekly",
      expectedEvidence: ["Forecast confidence", "Commit vs pipeline", "Slippage"],
      expectedRecommendation: "Address the largest forecast confidence drag",
      expectedExecutiveAction: "Challenge or confirm the forecast with sales leadership",
    },
    {
      id: "com-renewals-at-risk",
      name: "Renewals at risk",
      profileId: "commercial_executive",
      businessQuestion: "Which renewals are at risk?",
      expectedInsight: "Renewals likely to churn or compress without action",
      evidenceSources: ["salesforce", "knowledge_graph"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "At-risk renewals listed when available",
        "Risk reason attached",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Retention interventions before renewal loss",
      reviewFrequency: "weekly",
      expectedEvidence: ["Renewal dates", "Usage/health risk", "Competitor signals"],
      expectedRecommendation: "Execute retention play on top at-risk renewal",
      expectedExecutiveAction: "Assign renewal save owner and offer parameters",
    },
    {
      id: "com-customers-contact",
      name: "Customers to contact",
      profileId: "commercial_executive",
      businessQuestion: "Which customers should I contact?",
      expectedInsight: "Prioritised contact list for executive outreach",
      evidenceSources: ["salesforce", "microsoft365"],
      requiredProviders: ["microsoft365", "salesforce"],
      successCriteria: [
        "Contact recommendations present",
        "Why contact now is clear",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "High-leverage executive outreach completed",
      reviewFrequency: "daily",
      expectedEvidence: ["Strategic accounts", "Open opportunities", "Meeting gaps"],
      expectedRecommendation: "Contact the top recommended customer today",
      expectedExecutiveAction: "Make or schedule the outreach",
    },
    {
      id: "com-commercial-risks",
      name: "Commercial risks",
      profileId: "commercial_executive",
      businessQuestion: "Which commercial risks need attention?",
      expectedInsight: "Portfolio commercial risks requiring leadership attention",
      evidenceSources: ["salesforce", "council", "knowledge_graph"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "Commercial risks surfaced",
        "Severity / urgency clear",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Risks mitigated before they hit revenue",
      reviewFrequency: "daily",
      expectedEvidence: ["Pipeline concentration", "Discount pressure", "Deal risk flags"],
      expectedRecommendation: "Mitigate the highest commercial risk this week",
      expectedExecutiveAction: "Decide mitigation owner and checkpoint",
    },
    {
      id: "com-executive-coaching",
      name: "Executives needing coaching",
      profileId: "commercial_executive",
      businessQuestion: "Which executives need coaching?",
      expectedInsight: "Leaders whose pipeline or forecast hygiene needs coaching",
      evidenceSources: ["salesforce", "microsoft365"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "Coaching candidates identified when signals exist",
        "Coaching theme is specific",
        "Confidence ≥ 55",
      ],
      confidenceThreshold: 55,
      businessOutcome: "Sales leadership quality improves through targeted coaching",
      reviewFrequency: "weekly",
      expectedEvidence: ["Forecast quality gaps", "Stalled owned deals", "Activity gaps"],
      expectedRecommendation: "Coach the leader with the largest forecast gap",
      expectedExecutiveAction: "Book a coaching conversation this week",
    },
    {
      id: "com-revenue-risks",
      name: "Revenue risks",
      profileId: "commercial_executive",
      businessQuestion: "What revenue risks exist?",
      expectedInsight: "Near-term revenue risks across pipeline and renewals",
      evidenceSources: ["salesforce", "knowledge_graph"],
      requiredProviders: ["salesforce"],
      successCriteria: [
        "Revenue risks quantified or prioritised",
        "Time horizon clear",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Revenue plan protected through early action",
      reviewFrequency: "weekly",
      expectedEvidence: ["Commit risk", "Renewal risk", "Slippage value"],
      expectedRecommendation: "Protect the largest near-term revenue risk",
      expectedExecutiveAction: "Approve recovery plan for top revenue risk",
    },
    {
      id: "com-prioritise-today",
      name: "Priorities for today",
      profileId: "commercial_executive",
      businessQuestion: "What should I prioritise today?",
      expectedInsight: "Ranked commercial priorities for the executive day",
      evidenceSources: [
        "microsoft365",
        "salesforce",
        "council",
        "knowledge_graph",
      ],
      requiredProviders: ["microsoft365", "salesforce"],
      successCriteria: [
        "Today priorities / recommended actions present",
        "Mapped to commercial questions",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Executive day spent on highest-leverage commercial work",
      reviewFrequency: "daily",
      expectedEvidence: ["Recommended actions", "Agenda", "Overnight changes"],
      expectedRecommendation: "Execute the top commercial priority before midday",
      expectedExecutiveAction: "Commit to the top priority and next conversation",
    },
  ],
};
