import { InMemoryExecutiveMemoryStore } from "@/intelligence/executive-memory/store/in-memory-store";
import type { ExecutiveMemoryStore } from "@/intelligence/executive-memory/store/memory-store";
import type {
  ExecutiveCommitment,
  MemoryEvent,
} from "@/intelligence/executive-memory/types";

const EXEC = "exec-alex";

/**
 * Northline mock memory — traceable history for Helix, forums, board, capacity.
 * No invented insights: every sentence later must cite these event ids.
 */
export function createSeededExecutiveMemoryStore(): ExecutiveMemoryStore {
  const store = new InMemoryExecutiveMemoryStore({
    asOf: "2026-07-20T06:15:00+10:00",
    source: "mock-northline-memory",
  });

  const events: MemoryEvent[] = [
    {
      id: "mem-helix-1",
      at: "2026-06-09T09:00:00+10:00",
      kind: "risk_raised",
      entityKind: "risk",
      entityId: "risk-helix-window",
      label: "Helix residency gap surfaced",
      detail: "Security questionnaire stalled Helix expansion path.",
      source: "Overnight Signal Bus",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-enterprise-arr", "customer-helix"],
      tags: ["helix", "recurrence"],
    },
    {
      id: "mem-helix-2",
      at: "2026-06-23T09:00:00+10:00",
      kind: "risk_raised",
      entityKind: "risk",
      entityId: "risk-helix-window",
      label: "Helix residency gap resurfaced",
      detail: "Same residency posture gap blocked commercial motion again.",
      source: "Salesforce opportunity stage",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-enterprise-arr", "decision-residency"],
      tags: ["helix", "recurrence"],
    },
    {
      id: "mem-helix-3",
      at: "2026-07-07T09:00:00+10:00",
      kind: "risk_raised",
      entityKind: "risk",
      entityId: "risk-helix-window",
      label: "Helix residency gap — third occurrence",
      detail: "Procurement window pressure returned without written posture.",
      source: "CRO update",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-enterprise-arr", "decision-residency"],
      tags: ["helix", "recurrence"],
      metrics: { occurrence: 3 },
    },
    {
      id: "mem-meetings-baseline",
      at: "2026-06-10T08:00:00+10:00",
      kind: "meeting_held",
      entityKind: "behaviour",
      entityId: "behaviour-meeting-load",
      label: "Heavy leadership meeting load",
      detail: "Weekly leadership meeting hours sat at 14 before the forum commitment.",
      source: "Microsoft 365 calendar analytics",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-efficiency"],
      tags: ["meeting_load"],
      metrics: { meetingHours: 14 },
    },
    {
      id: "mem-commit-meetings",
      at: "2026-06-20T08:30:00+10:00",
      kind: "commitment_made",
      entityKind: "commitment",
      entityId: "commit-reduce-meetings",
      label: "Reduce duplicate leadership forums",
      detail: "Alex committed to collapsing Ops/Product forums within 30 days.",
      source: "ELT operating review",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-efficiency", "decision-forum"],
      tags: ["meeting_load", "commitment"],
    },
    {
      id: "mem-meetings-improve-1",
      at: "2026-07-01T08:00:00+10:00",
      kind: "meeting_held",
      entityKind: "behaviour",
      entityId: "behaviour-meeting-load",
      label: "Meeting load eased after forum commitment",
      detail: "Weekly leadership meeting hours dropped from 14 to 11.",
      source: "Microsoft 365 calendar analytics",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-efficiency", "commit-reduce-meetings"],
      tags: ["meeting_load", "improvement"],
      metrics: { meetingHours: 11, priorMeetingHours: 14 },
    },
    {
      id: "mem-meetings-improve-2",
      at: "2026-07-15T08:00:00+10:00",
      kind: "deep_work_protected",
      entityKind: "behaviour",
      entityId: "behaviour-deep-work",
      label: "Morning deep-work block held",
      detail: "Two consecutive Mondays protected 90-minute Focus blocks.",
      source: "Calendar guard",
      executiveId: EXEC,
      tags: ["deep_work", "improvement"],
      metrics: { deepWorkMinutes: 90 },
    },
    {
      id: "mem-rec-success",
      at: "2026-06-16T16:00:00+10:00",
      kind: "recommendation_succeeded",
      entityKind: "recommendation",
      entityId: "rec-historical-controls",
      label: "Compensating-controls path succeeded before",
      detail:
        "Prior enterprise exception with compensating controls unblocked Apex without board incident.",
      source: "Decision archive",
      executiveId: EXEC,
      relatedEntityIds: ["decision-residency", "outcome-enterprise-arr"],
      tags: ["recommendation_success"],
      metrics: { outcomeDelta: 8 },
    },
    {
      id: "mem-rec-failed",
      at: "2026-06-12T11:00:00+10:00",
      kind: "recommendation_failed",
      entityKind: "recommendation",
      entityId: "rec-historical-wait",
      label: "Wait-and-see on residency failed",
      detail: "Deferring a similar residency call lost a procurement window earlier this quarter.",
      source: "Decision archive",
      executiveId: EXEC,
      relatedEntityIds: ["decision-residency"],
      tags: ["recommendation_failure"],
      metrics: { outcomeDelta: -12 },
    },
    {
      id: "mem-decision-velocity",
      at: "2026-07-10T18:00:00+10:00",
      kind: "approval_latency",
      entityKind: "behaviour",
      entityId: "behaviour-approval-latency",
      label: "Approval latency rose on strategic calls",
      detail: "Median bind time on Focus Decisions increased from 2.1d to 3.4d.",
      source: "Decision Engine telemetry",
      executiveId: EXEC,
      tags: ["decision_velocity", "deterioration"],
      metrics: { latencyDays: 3.4, priorLatencyDays: 2.1 },
    },
    {
      id: "mem-delegation",
      at: "2026-07-08T10:00:00+10:00",
      kind: "delegation_made",
      entityKind: "action",
      entityId: "action-counsel-memo",
      label: "Delegated exception memo to counsel",
      detail: "Option paper preparation delegated; bind retained by CEO.",
      source: "Action Tracker",
      executiveId: EXEC,
      relatedEntityIds: ["decision-residency", "person-sam"],
      tags: ["delegation"],
    },
    {
      id: "mem-focus-drift",
      at: "2026-07-14T09:30:00+10:00",
      kind: "focus_shift",
      entityKind: "behaviour",
      entityId: "behaviour-strategic-focus",
      label: "Attention pulled to operational forums",
      detail: "Two unplanned operating reviews displaced a strategy block.",
      source: "Calendar guard",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-efficiency"],
      tags: ["strategic_focus", "drift"],
      metrics: { focusDrift: 18 },
    },
    {
      id: "mem-interrupt",
      at: "2026-07-18T11:15:00+10:00",
      kind: "interruption",
      entityKind: "behaviour",
      entityId: "behaviour-interruptions",
      label: "High interruption morning",
      detail: "Six context switches before noon across Slack and calendar.",
      source: "Attention telemetry",
      executiveId: EXEC,
      tags: ["interruptions"],
      metrics: { interruptions: 6 },
    },
    {
      id: "mem-outcome-arr",
      at: "2026-07-20T06:00:00+10:00",
      kind: "outcome_moved",
      entityKind: "outcome",
      entityId: "outcome-enterprise-arr",
      label: "Enterprise ARR drifted overnight",
      detail: "Health slipped after Helix delay signal.",
      source: "Outcome Engine",
      executiveId: EXEC,
      relatedEntityIds: ["signal-helix-slip", "decision-residency"],
      tags: ["helix"],
      metrics: { healthDelta: -6 },
    },
    {
      id: "mem-board-risk",
      at: "2026-07-19T15:00:00+10:00",
      kind: "risk_raised",
      entityKind: "risk",
      entityId: "risk-board-trust",
      label: "Board disclosure risk elevated",
      detail: "Incomplete Helix language threatens pack honesty.",
      source: "Board prep working session",
      executiveId: EXEC,
      relatedEntityIds: ["outcome-board", "decision-board-risk"],
      tags: ["board"],
    },
  ];

  store.appendMany(events);

  const commitments: ExecutiveCommitment[] = [
    {
      id: "commit-reduce-meetings",
      madeAt: "2026-06-20T08:30:00+10:00",
      dueAt: "2026-07-20T17:00:00+10:00",
      label: "Reduce duplicate leadership forums",
      detail: "Collapse Ops/Product forums within 30 days.",
      status: "open",
      entityKind: "commitment",
      entityId: "commit-reduce-meetings",
      executiveId: EXEC,
      sourceEventId: "mem-commit-meetings",
    },
    {
      id: "commit-helix-position",
      madeAt: "2026-07-13T09:00:00+10:00",
      dueAt: "2026-07-20T17:00:00+10:00",
      label: "Take written Helix residency position",
      detail: "CEO bind required before security workshop window closes.",
      status: "open",
      entityKind: "decision",
      entityId: "decision-residency",
      executiveId: EXEC,
      sourceEventId: "mem-helix-3",
    },
  ];

  for (const commitment of commitments) {
    store.upsertCommitment(commitment);
  }

  return store;
}
