/**
 * Operations Executive Scenario Pack — acceptance criteria.
 */

import type { ScenarioPack } from "@/scenarios/framework/types";

export const OPERATIONS_SCENARIO_PACK: ScenarioPack = {
  id: "pack-operations-executive",
  name: "Operations Executive Scenario Pack",
  profileId: "operations_executive",
  requiredProviders: ["microsoft365", "simpro"],
  description:
    "Executive questions Operations leaders must have answered every morning.",
  scenarios: [
    {
      id: "ops-overnight-changes",
      name: "Overnight changes",
      profileId: "operations_executive",
      businessQuestion: "What changed overnight?",
      expectedInsight:
        "A concise overnight delta covering jobs, capacity, customer risk, and safety.",
      evidenceSources: ["microsoft365", "simpro", "knowledge_graph"],
      requiredProviders: ["microsoft365", "simpro"],
      successCriteria: [
        "Overnight delta present in Today",
        "At least one material change surfaced when providers healthy",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Executive starts the day oriented without inbox triage",
      reviewFrequency: "daily",
      expectedEvidence: [
        "Jobs created/completed overnight",
        "Calendar / meeting shifts",
        "Capacity or SLA changes",
      ],
      expectedRecommendation:
        "Review the top overnight changes before the first meeting",
      expectedExecutiveAction: "Open Today and acknowledge material overnight items",
    },
    {
      id: "ops-jobs-attention",
      name: "Jobs requiring attention",
      profileId: "operations_executive",
      businessQuestion: "Which jobs require executive attention?",
      expectedInsight: "Prioritised jobs at risk with why they need escalation",
      evidenceSources: ["simpro", "knowledge_graph"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Jobs at risk listed when operational context available",
        "Each job has a reason for attention",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "At-risk work is intervened before customer impact",
      reviewFrequency: "daily",
      expectedEvidence: ["Jobs at risk", "SLA / schedule pressure", "Customer impact"],
      expectedRecommendation: "Escalate or reallocate the highest-risk job today",
      expectedExecutiveAction: "Assign owner and deadline for the top risk job",
    },
    {
      id: "ops-customers-at-risk",
      name: "Customers at risk",
      profileId: "operations_executive",
      businessQuestion: "Which customers are at risk?",
      expectedInsight: "Customers with delivery or relationship risk requiring contact",
      evidenceSources: ["simpro", "microsoft365", "knowledge_graph"],
      requiredProviders: ["microsoft365", "simpro"],
      successCriteria: [
        "Customer risk signals present or explicitly clear",
        "Link between operational failure and customer impact",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Proactive customer recovery before churn or complaint",
      reviewFrequency: "daily",
      expectedEvidence: ["Delivery failures", "Open complaints", "Repeated delays"],
      expectedRecommendation: "Contact the highest-risk customer today",
      expectedExecutiveAction: "Call or email the at-risk account sponsor",
    },
    {
      id: "ops-capacity-constrained",
      name: "Capacity constraints",
      profileId: "operations_executive",
      businessQuestion: "Where is operational capacity constrained?",
      expectedInsight: "Regions, crews, or skill pools under capacity pressure",
      evidenceSources: ["simpro"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Capacity bottlenecks identified",
        "Constraint location is specific",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Capacity rebalanced before service failure",
      reviewFrequency: "daily",
      expectedEvidence: ["Utilisation by crew/region", "Open job load", "Bottlenecks"],
      expectedRecommendation: "Shift work or add capacity where constrained",
      expectedExecutiveAction: "Approve reallocation or overtime for constrained area",
    },
    {
      id: "ops-technicians-overloaded",
      name: "Overloaded technicians",
      profileId: "operations_executive",
      businessQuestion: "Which technicians are overloaded?",
      expectedInsight: "Technicians above sustainable utilisation with risk of miss",
      evidenceSources: ["simpro"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Overloaded technicians listed when data present",
        "Utilisation or load evidence attached",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Prevent burnout and missed appointments",
      reviewFrequency: "daily",
      expectedEvidence: ["Technician utilisation", "Job counts", "Overtime signals"],
      expectedRecommendation: "Redistribute jobs from overloaded technicians",
      expectedExecutiveAction: "Instruct ops manager to rebalance today's board",
    },
    {
      id: "ops-revenue-threats",
      name: "Revenue-threatening issues",
      profileId: "operations_executive",
      businessQuestion: "Which operational issues threaten revenue?",
      expectedInsight: "Operational failures with clear revenue or cash impact",
      evidenceSources: ["simpro", "knowledge_graph"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Revenue-linked operational risks identified",
        "Cash / billing / delivery linkage explained",
        "Confidence ≥ 60",
      ],
      confidenceThreshold: 60,
      businessOutcome: "Protect revenue through operational intervention",
      reviewFrequency: "daily",
      expectedEvidence: ["Cash collection pressure", "Billable work delayed", "SLA credits"],
      expectedRecommendation: "Prioritise work that unlocks or protects revenue",
      expectedExecutiveAction: "Decide which revenue-critical jobs get resources first",
    },
    {
      id: "ops-projects-slipping",
      name: "Slipping projects",
      profileId: "operations_executive",
      businessQuestion: "Which projects are slipping?",
      expectedInsight: "Projects behind plan with slippage drivers",
      evidenceSources: ["simpro", "microsoft365", "knowledge_graph"],
      requiredProviders: ["microsoft365", "simpro"],
      successCriteria: [
        "Slipping projects or delivery commitments surfaced",
        "Driver of slip identified",
        "Confidence ≥ 55",
      ],
      confidenceThreshold: 55,
      businessOutcome: "Project recovery before contractual miss",
      reviewFrequency: "weekly",
      expectedEvidence: ["Schedule variance", "Open issues", "Meeting/decision blockers"],
      expectedRecommendation: "Intervene on the most slipped project this week",
      expectedExecutiveAction: "Hold a recovery checkpoint with the project owner",
    },
    {
      id: "ops-safety-escalation",
      name: "Safety escalation",
      profileId: "operations_executive",
      businessQuestion: "What safety issues require escalation?",
      expectedInsight: "Safety signals that need executive escalation now",
      evidenceSources: ["simpro", "microsoft365"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Safety signals present or explicitly none material",
        "Escalation path clear when signals exist",
        "Confidence ≥ 70 when safety items present",
      ],
      confidenceThreshold: 70,
      businessOutcome: "Safety issues escalated before harm",
      reviewFrequency: "daily",
      expectedEvidence: ["Safety incidents", "Near misses", "Open hazards"],
      expectedRecommendation: "Escalate material safety issues immediately",
      expectedExecutiveAction: "Confirm escalation owner and containment action",
    },
    {
      id: "ops-asset-risk",
      name: "Asset operational risk",
      profileId: "operations_executive",
      businessQuestion: "Which assets present operational risk?",
      expectedInsight: "Assets whose condition or availability threatens delivery",
      evidenceSources: ["simpro", "knowledge_graph"],
      requiredProviders: ["simpro"],
      successCriteria: [
        "Asset risk signals identified when available",
        "Operational impact explained",
        "Confidence ≥ 55",
      ],
      confidenceThreshold: 55,
      businessOutcome: "Prevent downtime from known asset risk",
      reviewFrequency: "weekly",
      expectedEvidence: ["Asset availability", "Maintenance backlog", "Critical asset flags"],
      expectedRecommendation: "Schedule maintenance or contingency for risky assets",
      expectedExecutiveAction: "Approve maintenance window or contingency plan",
    },
    {
      id: "ops-focus-today",
      name: "Focus for today",
      profileId: "operations_executive",
      businessQuestion: "What should I focus on today?",
      expectedInsight: "A ranked focus list for the executive day",
      evidenceSources: [
        "microsoft365",
        "simpro",
        "knowledge_graph",
        "council",
      ],
      requiredProviders: ["microsoft365", "simpro"],
      successCriteria: [
        "Today focus / recommended actions present",
        "Actions map to business questions",
        "Confidence ≥ 65",
      ],
      confidenceThreshold: 65,
      businessOutcome: "Executive attention spent on highest-leverage work",
      reviewFrequency: "daily",
      expectedEvidence: ["Recommended actions", "Agenda priorities", "Overnight changes"],
      expectedRecommendation: "Execute the top recommended action before midday",
      expectedExecutiveAction: "Commit to the top focus item and owner",
    },
  ],
};
