import { MANUFACTURING_ADVISOR_CATALOGUE } from "@/domain-advisors/catalogues/manufacturing";
import { MINING_ADVISOR_CATALOGUE } from "@/domain-advisors/catalogues/mining";
import { UTILITIES_ADVISOR_CATALOGUE } from "@/domain-advisors/catalogues/utilities";
import {
  CONSTRUCTION_ADVISOR_CATALOGUE,
  FIELD_SERVICES_ADVISOR_CATALOGUE,
  FINANCIAL_SERVICES_ADVISOR_CATALOGUE,
  GOVERNMENT_ADVISOR_CATALOGUE,
  HEALTHCARE_ADVISOR_CATALOGUE,
  LOGISTICS_ADVISOR_CATALOGUE,
  PROFESSIONAL_SERVICES_ADVISOR_CATALOGUE,
  RETAIL_ADVISOR_CATALOGUE,
  TECHNOLOGY_ADVISOR_CATALOGUE,
} from "@/domain-advisors/catalogues/remaining";
import type {
  DomainAdvisorCatalogue,
  DomainAdvisorIndustryId,
} from "@/domain-advisors/types";

export const ALL_DOMAIN_ADVISOR_CATALOGUES: DomainAdvisorCatalogue[] = [
  MANUFACTURING_ADVISOR_CATALOGUE,
  MINING_ADVISOR_CATALOGUE,
  UTILITIES_ADVISOR_CATALOGUE,
  CONSTRUCTION_ADVISOR_CATALOGUE,
  HEALTHCARE_ADVISOR_CATALOGUE,
  GOVERNMENT_ADVISOR_CATALOGUE,
  TECHNOLOGY_ADVISOR_CATALOGUE,
  FINANCIAL_SERVICES_ADVISOR_CATALOGUE,
  RETAIL_ADVISOR_CATALOGUE,
  PROFESSIONAL_SERVICES_ADVISOR_CATALOGUE,
  FIELD_SERVICES_ADVISOR_CATALOGUE,
  LOGISTICS_ADVISOR_CATALOGUE,
];

export function getDomainAdvisorCatalogue(
  industry: DomainAdvisorIndustryId,
): DomainAdvisorCatalogue | undefined {
  return ALL_DOMAIN_ADVISOR_CATALOGUES.find((c) => c.industry === industry);
}

export {
  MANUFACTURING_ADVISOR_CATALOGUE,
  MINING_ADVISOR_CATALOGUE,
  UTILITIES_ADVISOR_CATALOGUE,
  CONSTRUCTION_ADVISOR_CATALOGUE,
  HEALTHCARE_ADVISOR_CATALOGUE,
  GOVERNMENT_ADVISOR_CATALOGUE,
  TECHNOLOGY_ADVISOR_CATALOGUE,
  FINANCIAL_SERVICES_ADVISOR_CATALOGUE,
  RETAIL_ADVISOR_CATALOGUE,
  PROFESSIONAL_SERVICES_ADVISOR_CATALOGUE,
  FIELD_SERVICES_ADVISOR_CATALOGUE,
  LOGISTICS_ADVISOR_CATALOGUE,
};
