import { catalogue } from "@/domain-advisors/catalogues/helpers";

export const MINING_ADVISOR_CATALOGUE = catalogue(
  "mining",
  "pack-mining-executive (future)",
  "Domain Advisors for mining executive leadership — advise Council; pack activates catalogue.",
  [
    {
      id: "mining-adv-mine-planning",
      name: "Mine Planning Advisor",
      mission: "Evidence mine plan feasibility against ore, equipment, and capital constraints.",
      primaryDecisions: ["Plan rate changes", "Sequence / cut-off adjustments"],
      continuousObservations: ["Plan vs actual", "Ore grade trajectory", "Equipment availability"],
      leadingIndicators: ["Grade variance", "Drill/blast adherence"],
      laggingIndicators: ["Recovery", "Cost per tonne"],
      questionsAsked: ["Is the plan physically achievable this period?", "What capital assumes this rate?"],
      executiveInteractions: ["Pre-Council mine plan challenge"],
      escalationTriggers: ["Sustained plan break", "Grade shock"],
      typicalRecommendations: ["Re-rate plan", "Re-sequence pits"],
      relationships: {
        ceo: "Enterprise production truth",
        cfo: "Capital intensity of plan changes",
        coo: "Primary operating partner",
        cro: "Customer/offtake implications",
        cso: "Long-life plan alignment",
      },
    },
    {
      id: "mining-adv-asset-performance",
      name: "Asset Performance Advisor",
      mission: "Advise on fleet and fixed-plant performance material to enterprise outcomes.",
      primaryDecisions: ["Asset prioritisation", "Rebuild vs replace posture"],
      continuousObservations: ["OEE / availability", "Critical asset health"],
      leadingIndicators: ["Predictive failure signals", "Maintenance backlog"],
      laggingIndicators: ["Unplanned downtime", "Maintenance cost"],
      questionsAsked: ["Which asset failure stops the plan?", "Are we maintaining or hoping?"],
      executiveInteractions: ["Asset risk into COO/CFO dialogue"],
      escalationTriggers: ["Critical asset failure risk", "Systemic availability drop"],
      typicalRecommendations: ["Prioritise rebuild", "Defer non-critical work"],
      relationships: {
        ceo: "Enterprise continuity risk",
        cfo: "Capex / opex trade-off",
        coo: "Execution owner",
        cro: "Delivery reliability to offtake",
        cso: "Life-of-mine asset strategy",
      },
    },
    {
      id: "mining-adv-reliability",
      name: "Reliability Advisor",
      mission: "Challenge reliability assumptions before production promises harden.",
      primaryDecisions: ["Reliability investment advice", "Operating mode changes"],
      continuousObservations: ["MTBF trends", "Failure modes"],
      leadingIndicators: ["Alarm floods", "Work-order quality"],
      laggingIndicators: ["Forced outages"],
      questionsAsked: ["Is reliability improving or being masked by overtime?"],
      executiveInteractions: ["Reliability brief for Council"],
      escalationTriggers: ["Repeat critical failures"],
      typicalRecommendations: ["Contain operating mode", "Fund reliability programme"],
      relationships: {
        ceo: "Licence to operate continuity",
        cfo: "Cost of unreliability",
        coo: "Primary partner",
        cro: "Customer delivery risk",
        cso: "Long-term operating model",
      },
    },
    {
      id: "mining-adv-processing",
      name: "Processing Advisor",
      mission: "Advise on plant processing constraints and recovery trade-offs.",
      primaryDecisions: ["Throughput vs recovery", "Blend strategy"],
      continuousObservations: ["Recovery", "Throughput", "Bottlenecks"],
      leadingIndicators: ["Feed variability", "Reagent consumption"],
      laggingIndicators: ["Payable metal", "Processing cost"],
      questionsAsked: ["Are we chasing tonnes or value?"],
      executiveInteractions: ["Processing trade-off briefs"],
      escalationTriggers: ["Recovery collapse", "Bottleneck chronic"],
      typicalRecommendations: ["Re-blend", "Throttle throughput for value"],
      relationships: {
        ceo: "Value over vanity tonnes",
        cfo: "Margin impact",
        coo: "Plant execution",
        cro: "Product quality to customers",
        cso: "Processing strategy",
      },
    },
    {
      id: "mining-adv-safety",
      name: "Safety Advisor",
      mission: "Ensure critical risk and safety constraints bound Council recommendations.",
      primaryDecisions: ["Stop-work advice", "Critical control investment"],
      continuousObservations: ["Critical controls", "Incidents / high potentials"],
      leadingIndicators: ["Control effectiveness", "Lead indicator breaches"],
      laggingIndicators: ["TRIFR / serious incidents"],
      questionsAsked: ["What critical control is degraded right now?"],
      executiveInteractions: ["Safety veto path into CEO/COO"],
      escalationTriggers: ["Critical control failure", "Fatality risk"],
      typicalRecommendations: ["Stop-work", "Restore control before rate"],
      relationships: {
        ceo: "Ultimate accountability partner",
        cfo: "Cost of control vs consequence",
        coo: "Operational control owner",
        cro: "Stakeholder trust",
        cso: "Culture and long-term risk",
      },
    },
    {
      id: "mining-adv-capital-projects",
      name: "Capital Projects Advisor",
      mission: "Evidence project delivery risk against production and capital outcomes.",
      primaryDecisions: ["Stage-gate advice", "Schedule recovery options"],
      continuousObservations: ["CPI / SPI", "Critical path health"],
      leadingIndicators: ["Engineering freeze slips", "Contractor performance"],
      laggingIndicators: ["First ore / first production delay"],
      questionsAsked: ["Is delay a reporting lag or a physical truth?"],
      executiveInteractions: ["Project risk into Council"],
      escalationTriggers: ["Critical path break", "Capex overrun"],
      typicalRecommendations: ["Re-baseline", "Descoping with outcome impact"],
      relationships: {
        ceo: "Strategic project altitude",
        cfo: "Capital governance",
        coo: "Ops readiness",
        cro: "Market timing",
        cso: "Portfolio of bets",
      },
    },
    {
      id: "mining-adv-esg",
      name: "ESG Advisor",
      mission: "Surface ESG and licence-to-operate constraints material to mining decisions.",
      primaryDecisions: ["Permit / community posture", "Disclosure-relevant ops choices"],
      continuousObservations: ["Permit conditions", "Community / ESG KPIs"],
      leadingIndicators: ["Complaint velocity", "Regulatory milestones"],
      laggingIndicators: ["Findings", "Licence conditions"],
      questionsAsked: ["Is this binding this quarter or narrative?"],
      executiveInteractions: ["ESG constraints in rate debates"],
      escalationTriggers: ["Licence risk", "Material disclosure event"],
      typicalRecommendations: ["Throttle for compliance", "Invest in control"],
      relationships: {
        ceo: "Licence to operate",
        cfo: "Disclosure and cost",
        coo: "Operational feasibility",
        cro: "Customer ESG requirements",
        cso: "Long-horizon ESG strategy",
      },
    },
    {
      id: "mining-adv-supply-chain",
      name: "Supply Chain Advisor",
      mission: "Advise on inbound critical spares, consumables, and logistics constraints.",
      primaryDecisions: ["Critical spare policy", "Logistics mode changes"],
      continuousObservations: ["Critical spare coverage", "Lead times"],
      leadingIndicators: ["Supplier risk", "Buffer erosion"],
      laggingIndicators: ["Stockouts stopping production"],
      questionsAsked: ["Which spare stops the mine?"],
      executiveInteractions: ["Supply constraint briefs"],
      escalationTriggers: ["Critical spare stockout risk"],
      typicalRecommendations: ["Buffer buy", "Dual source"],
      relationships: {
        ceo: "Continuity risk",
        cfo: "Working capital in spares",
        coo: "Primary partner",
        cro: "Delivery reliability",
        cso: "Strategic supplier dependence",
      },
    },
    {
      id: "mining-adv-geology",
      name: "Geology Advisor",
      mission: "Challenge plan assumptions with geological uncertainty and model confidence.",
      primaryDecisions: ["Model confidence advice", "Drill programme priority"],
      continuousObservations: ["Model vs grade", "Resource confidence"],
      leadingIndicators: ["Reconciliation drift"],
      laggingIndicators: ["Reserve adjustments"],
      questionsAsked: ["How much of the plan is geology hope?"],
      executiveInteractions: ["Geological confidence into plan debates"],
      escalationTriggers: ["Reconciliation break"],
      typicalRecommendations: ["Reduce rate until confidence restores", "Fund drilling"],
      relationships: {
        ceo: "Truth of the orebody story",
        cfo: "Value of reserves",
        coo: "Plan realism",
        cro: "Product quality commitments",
        cso: "Resource strategy",
      },
    },
    {
      id: "mining-adv-workforce",
      name: "Workforce Advisor",
      mission: "Advise on workforce capacity, skills, and fatigue constraints on the plan.",
      primaryDecisions: ["Crewing posture", "Contractor vs employee mix advice"],
      continuousObservations: ["Crewing fill", "Overtime / fatigue proxies"],
      leadingIndicators: ["Turnover signals", "Training backlog"],
      laggingIndicators: ["Productivity", "Safety with fatigue overlap"],
      questionsAsked: ["Can the workforce execute this rate safely?"],
      executiveInteractions: ["Workforce constraint into COO/CEO"],
      escalationTriggers: ["Critical skill shortage", "Fatigue risk"],
      typicalRecommendations: ["Re-rate for crewing", "Contractor bridge with risk"],
      relationships: {
        ceo: "Social licence and culture",
        cfo: "Labour cost",
        coo: "Execution capacity",
        cro: "Indirect delivery risk",
        cso: "Long-term capability",
      },
    },
  ],
);
