import { catalogue } from "@/domain-advisors/catalogues/helpers";

export const UTILITIES_ADVISOR_CATALOGUE = catalogue(
  "utilities",
  "pack-utilities-executive (future)",
  "Domain Advisors for utilities executive leadership — network, assets, outages, capital, regulation.",
  [
    {
      id: "util-adv-network-operations",
      name: "Network Operations Advisor",
      mission: "Evidence network operating risk and performance for Council judgement.",
      primaryDecisions: ["Operating mode", "Load / switching posture"],
      continuousObservations: ["Network loading", "Constraint points"],
      leadingIndicators: ["Constraint hours", "Switching backlog"],
      laggingIndicators: ["SAIDI / SAIFI components"],
      questionsAsked: ["Where is the network actually constrained tonight?"],
      executiveInteractions: ["Network risk pre-Council"],
      escalationTriggers: ["Systemic constraint", "Cascade risk"],
      typicalRecommendations: ["Reconfigure", "Throttle demand programmes"],
      relationships: {
        ceo: "System reliability altitude",
        cfo: "Cost of operating modes",
        coo: "Primary partner",
        cro: "Customer impact",
        cso: "Network strategy",
      },
    },
    {
      id: "util-adv-asset-health",
      name: "Asset Health Advisor",
      mission: "Advise on asset condition risk material to reliability and capital plans.",
      primaryDecisions: ["Replace vs refurbish advice", "Inspection priority"],
      continuousObservations: ["Condition scores", "Critical asset watchlist"],
      leadingIndicators: ["Condition degradation velocity"],
      laggingIndicators: ["Failure events", "Unplanned opex"],
      questionsAsked: ["Which asset failure creates a public incident?"],
      executiveInteractions: ["Asset health into capital debates"],
      escalationTriggers: ["Critical asset red"],
      typicalRecommendations: ["Bring forward replace", "Increase inspection"],
      relationships: {
        ceo: "Public reliability risk",
        cfo: "Capital timing",
        coo: "Maintenance execution",
        cro: "Customer reliability promises",
        cso: "Long-term asset strategy",
      },
    },
    {
      id: "util-adv-outages",
      name: "Outages Advisor",
      mission: "Challenge outage plans and restoration readiness before commitments.",
      primaryDecisions: ["Planned outage windows", "Storm / contingency posture"],
      continuousObservations: ["Outage backlog", "Restoration metrics"],
      leadingIndicators: ["Crew readiness", "Weather / contingency signals"],
      laggingIndicators: ["Customer minutes lost"],
      questionsAsked: ["Is restoration capacity real or assumed?"],
      executiveInteractions: ["Outage risk briefs"],
      escalationTriggers: ["Major event risk", "Chronic restoration miss"],
      typicalRecommendations: ["Defer planned outage", "Surge crew plan"],
      relationships: {
        ceo: "Public accountability",
        cfo: "Cost of events",
        coo: "Restoration owner",
        cro: "Customer communications",
        cso: "Resilience strategy",
      },
    },
    {
      id: "util-adv-capital-delivery",
      name: "Capital Delivery Advisor",
      mission: "Evidence capital programme delivery against reliability outcomes.",
      primaryDecisions: ["Programme re-baseline", "Portfolio re-prioritisation"],
      continuousObservations: ["CPI / SPI", "Connection backlog"],
      leadingIndicators: ["Permit / land slips", "Contractor performance"],
      laggingIndicators: ["Energisation delay"],
      questionsAsked: ["Which delayed project creates the next reliability gap?"],
      executiveInteractions: ["Capital delivery into Council"],
      escalationTriggers: ["Critical project break"],
      typicalRecommendations: ["Reprioritise portfolio", "Re-baseline with disclosure"],
      relationships: {
        ceo: "Strategic delivery",
        cfo: "Capital governance",
        coo: "Ops readiness",
        cro: "Customer connection promises",
        cso: "Network investment strategy",
      },
    },
    {
      id: "util-adv-regulatory",
      name: "Regulatory Advisor",
      mission: "Surface regulatory constraints and incentive risks on operating decisions.",
      primaryDecisions: ["Compliance posture", "Incentive / penalty trade-offs"],
      continuousObservations: ["Regulatory milestones", "Compliance findings"],
      leadingIndicators: ["Filing readiness", "Audit signals"],
      laggingIndicators: ["Penalties", "Licence conditions"],
      questionsAsked: ["Does this operating choice create regulatory exposure?"],
      executiveInteractions: ["Regulatory constraint briefs"],
      escalationTriggers: ["Material non-compliance risk"],
      typicalRecommendations: ["Operate within envelope", "Disclose and remediate"],
      relationships: {
        ceo: "Licence and reputation",
        cfo: "Penalty / incentive economics",
        coo: "Operational compliance",
        cro: "Customer obligation framing",
        cso: "Regulatory strategy",
      },
    },
    {
      id: "util-adv-customer-reliability",
      name: "Customer Reliability Advisor",
      mission: "Translate network performance into customer-outcome stakes for Council.",
      primaryDecisions: ["Priority feeders / customers", "Compensation posture advice"],
      continuousObservations: ["Worst-served customers", "Complaint / claim trends"],
      leadingIndicators: ["Repeat interruption clusters"],
      laggingIndicators: ["Customer satisfaction / ombuds"],
      questionsAsked: ["Who experiences the reliability we report?"],
      executiveInteractions: ["Customer reliability challenge to averages"],
      escalationTriggers: ["Worst-served breach", "Ombuds surge"],
      typicalRecommendations: ["Target investment", "Customer remedy plan"],
      relationships: {
        ceo: "Public fairness",
        cfo: "Compensation cost",
        coo: "Targeted ops response",
        cro: "Primary customer partner",
        cso: "Service promise strategy",
      },
    },
    {
      id: "util-adv-field-workforce",
      name: "Field Workforce Advisor",
      mission: "Advise on field crew capacity and fatigue constraints on restoration and works.",
      primaryDecisions: ["Crew surge", "Contractor mobilisation"],
      continuousObservations: ["Crew availability", "Overtime / fatigue"],
      leadingIndicators: ["Vacancy", "Training backlog"],
      laggingIndicators: ["Jobs completed", "Safety with fatigue"],
      questionsAsked: ["Can the field force execute the plan safely?"],
      executiveInteractions: ["Workforce constraint into outage plans"],
      escalationTriggers: ["Crew shortage in event window"],
      typicalRecommendations: ["Mobilise contractors", "Defer non-critical works"],
      relationships: {
        ceo: "Safety and service",
        cfo: "Labour cost",
        coo: "Primary partner",
        cro: "Customer wait times",
        cso: "Capability strategy",
      },
    },
    {
      id: "util-adv-generation",
      name: "Generation Advisor",
      mission: "Advise on generation / energy supply constraints where material to the utility.",
      primaryDecisions: ["Dispatch / availability posture", "Outage of generation assets"],
      continuousObservations: ["Availability", "Fuel / resource constraints"],
      leadingIndicators: ["Forced outage risk"],
      laggingIndicators: ["Unserved energy"],
      questionsAsked: ["What generation assumption is the plan relying on?"],
      executiveInteractions: ["Generation risk into Council"],
      escalationTriggers: ["Capacity shortfall risk"],
      typicalRecommendations: ["Secure cover", "Defer coincident outages"],
      relationships: {
        ceo: "System adequacy",
        cfo: "Energy cost",
        coo: "Asset operations",
        cro: "Wholesale / customer price impact",
        cso: "Energy strategy",
      },
    },
    {
      id: "util-adv-sustainability",
      name: "Sustainability Advisor",
      mission: "Bring emissions and sustainability constraints into utilities judgement early.",
      primaryDecisions: ["Decarbonisation pace vs reliability", "Disclosure-relevant ops"],
      continuousObservations: ["Emissions trajectory", "Customer / policy requirements"],
      leadingIndicators: ["Policy milestone proximity"],
      laggingIndicators: ["Reported emissions"],
      questionsAsked: ["Is the constraint binding this period?"],
      executiveInteractions: ["Sustainability in capital and ops debates"],
      escalationTriggers: ["Policy miss risk"],
      typicalRecommendations: ["Adjust plan", "Invest to unlock"],
      relationships: {
        ceo: "Licence and policy",
        cfo: "Transition cost",
        coo: "Operational feasibility",
        cro: "Customer expectations",
        cso: "Transition strategy",
      },
    },
  ],
);
