import type { PackBusinessEvent } from "@/intelligence-packs/contract";

/** Phase 48 doc 04 — 18 executive business events */
export const MANUFACTURING_EVENTS: PackBusinessEvent[] = [
  {
    id: "mfg-evt-demand-collapse",
    label: "Regional demand collapse",
    description: "Construction activity drop + dealer cancel/push spike in regions",
    severity: "critical",
    eventClass: "demand_shock",
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-utilisation",
      "mfg-outcome-inventory",
      "mfg-outcome-working-capital",
    ],
    relatedOntologyTermIds: [
      "mfg-term-region",
      "mfg-term-dealer",
      "mfg-term-order-bank",
      "mfg-term-construction",
    ],
    executiveQuestion: "Reset the plan now, or ride it out?",
  },
  {
    id: "mfg-evt-demand-surge",
    label: "Unexpected demand surge",
    description: "Order bank exceeds capacity envelope for sustained weeks",
    severity: "high",
    eventClass: "demand_shock",
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-utilisation",
      "mfg-outcome-dealer",
      "mfg-outcome-lead-time",
    ],
    relatedOntologyTermIds: [
      "mfg-term-order-bank",
      "mfg-term-build-slot",
      "mfg-term-capacity-envelope",
    ],
    executiveQuestion: "Which build slots and dealers get scarce capacity?",
  },
  {
    id: "mfg-evt-supplier-outage",
    label: "Critical supplier outage",
    description: "Single-source part OTIF collapse; line stop risk",
    severity: "critical",
    eventClass: "supply_disruption",
    relatedOutcomeIds: [
      "mfg-outcome-supply-resilience",
      "mfg-outcome-utilisation",
      "mfg-outcome-lead-time",
    ],
    relatedOntologyTermIds: ["mfg-term-supplier", "mfg-term-part", "mfg-term-factory"],
    executiveQuestion: "Dual-source, buffer, or stop selling?",
  },
  {
    id: "mfg-evt-commodity-spike",
    label: "Commodity price spike",
    description: "Input cost shock sustained; competitor response mixed",
    severity: "high",
    eventClass: "cost_shock",
    relatedOutcomeIds: [
      "mfg-outcome-margin",
      "mfg-outcome-working-capital",
      "mfg-outcome-share",
    ],
    relatedOntologyTermIds: ["mfg-term-commodity"],
    executiveQuestion: "Pass through, absorb, or hybrid — for how long?",
  },
  {
    id: "mfg-evt-line-down",
    label: "Major line down",
    description: "Major line unavailable; promise breaches cascading",
    severity: "critical",
    eventClass: "operational_outage",
    relatedOutcomeIds: [
      "mfg-outcome-utilisation",
      "mfg-outcome-lead-time",
      "mfg-outcome-margin",
    ],
    relatedOntologyTermIds: ["mfg-term-line", "mfg-term-factory", "mfg-term-build-slot"],
    executiveQuestion: "Reallocate slots or declare channel impact?",
  },
  {
    id: "mfg-evt-quality-escape",
    label: "Field quality escape",
    description: "Field quality issue requiring contain, disclose, rework",
    severity: "critical",
    eventClass: "quality_event",
    relatedOutcomeIds: [
      "mfg-outcome-margin",
      "mfg-outcome-dealer",
      "mfg-outcome-share",
    ],
    relatedOntologyTermIds: ["mfg-term-model", "mfg-term-dealer"],
    executiveQuestion: "Contain, disclose, and rework — what is board language?",
  },
  {
    id: "mfg-evt-inventory-bloat",
    label: "Inventory bloat detected",
    description: "DIO above band; dealer inventory swollen",
    severity: "high",
    eventClass: "working_capital",
    relatedOutcomeIds: [
      "mfg-outcome-inventory",
      "mfg-outcome-working-capital",
      "mfg-outcome-dealer",
    ],
    relatedOntologyTermIds: ["mfg-term-inventory", "mfg-term-eo", "mfg-term-dealer"],
    executiveQuestion: "Destock posture — how deep, how fast?",
  },
  {
    id: "mfg-evt-eo-spike",
    label: "E&O spike",
    description: "Excess and obsolete inventory rising",
    severity: "high",
    eventClass: "working_capital",
    relatedOutcomeIds: [
      "mfg-outcome-inventory",
      "mfg-outcome-working-capital",
      "mfg-outcome-margin",
    ],
    relatedOntologyTermIds: ["mfg-term-eo", "mfg-term-inventory"],
    executiveQuestion: "Write-down now or recover via clearance?",
  },
  {
    id: "mfg-evt-allocation-conflict",
    label: "Dealer allocation conflict",
    description: "Strategic dealer vs high-turn dealer fighting same slots",
    severity: "high",
    eventClass: "channel_conflict",
    relatedOutcomeIds: [
      "mfg-outcome-dealer",
      "mfg-outcome-share",
      "mfg-outcome-lead-time",
    ],
    relatedOntologyTermIds: [
      "mfg-term-allocation",
      "mfg-term-dealer",
      "mfg-term-build-slot",
    ],
    executiveQuestion: "Whose scarcity rules win this week?",
  },
  {
    id: "mfg-evt-forecast-miss",
    label: "Material forecast miss",
    description: "Plan error material enough to force mid-cycle judgement",
    severity: "high",
    eventClass: "forecast_break",
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-inventory",
      "mfg-outcome-utilisation",
    ],
    relatedOntologyTermIds: ["mfg-term-order-bank", "mfg-term-region"],
    executiveQuestion: "Mid-cycle reset — yes/no, which regions?",
  },
  {
    id: "mfg-evt-overtime-spiral",
    label: "Overtime spiral",
    description: "Overtime above cap; OTTP held only via hot orders",
    severity: "high",
    eventClass: "capacity_stress",
    relatedOutcomeIds: [
      "mfg-outcome-utilisation",
      "mfg-outcome-margin",
      "mfg-outcome-lead-time",
    ],
    relatedOntologyTermIds: [
      "mfg-term-capacity-envelope",
      "mfg-term-expedite",
      "mfg-term-factory",
    ],
    executiveQuestion: "Reject overtime and slip promises, or accept structural cost?",
  },
  {
    id: "mfg-evt-construction-down",
    label: "Construction activity drop",
    description: "Leading indicator softens before factories feel it",
    severity: "moderate",
    eventClass: "macro_signal",
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-dealer",
      "mfg-outcome-share",
    ],
    relatedOntologyTermIds: ["mfg-term-construction", "mfg-term-region"],
    executiveQuestion: "Adjust regional outlook before factories feel it?",
  },
  {
    id: "mfg-evt-dealer-distress",
    label: "Strategic dealer distress",
    description: "Key dealer health deteriorates",
    severity: "high",
    eventClass: "channel_risk",
    relatedOutcomeIds: [
      "mfg-outcome-dealer",
      "mfg-outcome-working-capital",
      "mfg-outcome-share",
    ],
    relatedOntologyTermIds: ["mfg-term-dealer", "mfg-term-region"],
    executiveQuestion: "Support, restructure territory, or exit?",
  },
  {
    id: "mfg-evt-competitor-capacity",
    label: "Competitor capacity move",
    description: "Competitor announces capacity while local utilisation hot",
    severity: "moderate",
    eventClass: "competitive",
    relatedOutcomeIds: [
      "mfg-outcome-share",
      "mfg-outcome-future-fit",
      "mfg-outcome-utilisation",
    ],
    relatedOntologyTermIds: ["mfg-term-capacity-envelope", "mfg-term-automation"],
    executiveQuestion: "Accelerate or hold our capacity/automation bet?",
  },
  {
    id: "mfg-evt-electrification-shift",
    label: "Electrification demand shift",
    description: "Strategy model order bank jumps; legacy dealers resist",
    severity: "high",
    eventClass: "strategic_shift",
    relatedOutcomeIds: [
      "mfg-outcome-future-fit",
      "mfg-outcome-share",
      "mfg-outcome-inventory",
    ],
    relatedOntologyTermIds: [
      "mfg-term-electrification",
      "mfg-term-mix",
      "mfg-term-model",
    ],
    executiveQuestion: "Rebalance mix and capex gates this quarter?",
  },
  {
    id: "mfg-evt-board-inventory",
    label: "Board inventory challenge",
    description: "Board asks for inventory remediation narrative",
    severity: "high",
    eventClass: "governance",
    relatedOutcomeIds: ["mfg-outcome-working-capital", "mfg-outcome-inventory"],
    relatedOntologyTermIds: ["mfg-term-working-capital", "mfg-term-eo"],
    executiveQuestion: "What honest narrative and remediation do we take?",
  },
  {
    id: "mfg-evt-safety-stop",
    label: "Safety stoppage",
    description: "Safety stop; restart criteria and communication required",
    severity: "critical",
    eventClass: "safety",
    relatedOutcomeIds: [
      "mfg-outcome-utilisation",
      "mfg-outcome-supply-resilience",
    ],
    relatedOntologyTermIds: ["mfg-term-factory", "mfg-term-line"],
    executiveQuestion: "Restart criteria and external communication?",
  },
  {
    id: "mfg-evt-logistics-break",
    label: "Logistics / port disruption",
    description: "Inbound/outbound logistics break affecting promises",
    severity: "high",
    eventClass: "supply_disruption",
    relatedOutcomeIds: [
      "mfg-outcome-lead-time",
      "mfg-outcome-inventory",
      "mfg-outcome-working-capital",
    ],
    relatedOntologyTermIds: ["mfg-term-supplier", "mfg-term-inventory", "mfg-term-lead-time"],
    executiveQuestion: "Air freight exception or promise reset?",
  },
];
