import type { PackKpiDefinition } from "@/intelligence-packs/contract";

/**
 * Phase 48 doc 06.
 * Target-band KPIs mapped to nearest EIPF polarity; band discipline lives in reasoning rules.
 */
export const MANUFACTURING_KPIS: PackKpiDefinition[] = [
  {
    id: "mfg-kpi-dio",
    label: "Days inventory outstanding",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "Cash tied in stock relative to demand (within service floor)",
    linkedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-working-capital"],
  },
  {
    id: "mfg-kpi-eo-pct",
    label: "Excess & obsolete %",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Capital at risk of write-off",
    linkedOutcomeIds: [
      "mfg-outcome-inventory",
      "mfg-outcome-working-capital",
      "mfg-outcome-margin",
    ],
  },
  {
    id: "mfg-kpi-fill-rate",
    label: "Order fill rate",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Service level to dealers/customers",
    linkedOutcomeIds: [
      "mfg-outcome-inventory",
      "mfg-outcome-dealer",
      "mfg-outcome-lead-time",
    ],
  },
  {
    id: "mfg-kpi-wip-turns",
    label: "WIP turns",
    unit: "turns",
    polarity: "higher_better",
    executiveMeaning: "Flow health inside factories",
    linkedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-utilisation"],
  },
  {
    id: "mfg-kpi-forecast-wape",
    label: "Forecast WAPE",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Plan error magnitude",
    linkedOutcomeIds: ["mfg-outcome-forecast"],
  },
  {
    id: "mfg-kpi-forecast-bias",
    label: "Forecast bias",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Systematic over/under forecasting (band enforced by reasoning)",
    linkedOutcomeIds: ["mfg-outcome-forecast", "mfg-outcome-inventory"],
  },
  {
    id: "mfg-kpi-schedule-stability",
    label: "Frozen-window stability",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Plan discipline",
    linkedOutcomeIds: ["mfg-outcome-forecast", "mfg-outcome-utilisation"],
  },
  {
    id: "mfg-kpi-utilisation",
    label: "Factory utilisation",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Productive use of capacity envelope (healthy band ~75–90%)",
    linkedOutcomeIds: ["mfg-outcome-utilisation"],
  },
  {
    id: "mfg-kpi-oee",
    label: "OEE",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Quality of capacity use",
    linkedOutcomeIds: ["mfg-outcome-utilisation", "mfg-outcome-margin"],
  },
  {
    id: "mfg-kpi-overtime-pct",
    label: "Overtime hours %",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Structural stress / fake capacity",
    linkedOutcomeIds: ["mfg-outcome-utilisation", "mfg-outcome-margin"],
  },
  {
    id: "mfg-kpi-changeover-loss",
    label: "Changeover loss",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Mix complexity cost",
    linkedOutcomeIds: ["mfg-outcome-utilisation", "mfg-outcome-margin"],
  },
  {
    id: "mfg-kpi-dealer-fill",
    label: "Dealer fill rate",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Channel service",
    linkedOutcomeIds: ["mfg-outcome-dealer"],
  },
  {
    id: "mfg-kpi-dealer-dio",
    label: "Dealer days inventory",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "Channel inventory health (band via reasoning)",
    linkedOutcomeIds: ["mfg-outcome-dealer", "mfg-outcome-working-capital"],
  },
  {
    id: "mfg-kpi-dealer-turn",
    label: "Dealer inventory turn",
    unit: "turns",
    polarity: "higher_better",
    executiveMeaning: "Channel velocity",
    linkedOutcomeIds: ["mfg-outcome-dealer"],
  },
  {
    id: "mfg-kpi-lost-sales",
    label: "Lost sales (est.)",
    unit: "currency",
    polarity: "lower_better",
    executiveMeaning: "Scarcity / availability failure",
    linkedOutcomeIds: ["mfg-outcome-dealer", "mfg-outcome-share"],
  },
  {
    id: "mfg-kpi-ccc",
    label: "Cash conversion cycle",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "End-to-end cash speed",
    linkedOutcomeIds: ["mfg-outcome-working-capital"],
  },
  {
    id: "mfg-kpi-inventory-dollars",
    label: "Inventory $",
    unit: "currency",
    polarity: "lower_better",
    executiveMeaning: "Absolute capital in stock (context via narrative)",
    linkedOutcomeIds: ["mfg-outcome-working-capital", "mfg-outcome-inventory"],
  },
  {
    id: "mfg-kpi-dso",
    label: "Days sales outstanding",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "Receivables drag",
    linkedOutcomeIds: ["mfg-outcome-working-capital"],
  },
  {
    id: "mfg-kpi-dpo",
    label: "Days payable outstanding",
    unit: "days",
    polarity: "higher_better",
    executiveMeaning: "Payables policy (not maximise blindly)",
    linkedOutcomeIds: ["mfg-outcome-working-capital"],
  },
  {
    id: "mfg-kpi-ottp",
    label: "On-time-to-promise",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Promise integrity",
    linkedOutcomeIds: ["mfg-outcome-lead-time", "mfg-outcome-dealer"],
  },
  {
    id: "mfg-kpi-quoted-lead-time",
    label: "Quoted lead time",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "Competitiveness vs honesty",
    linkedOutcomeIds: ["mfg-outcome-lead-time", "mfg-outcome-share"],
  },
  {
    id: "mfg-kpi-expedite-rate",
    label: "Expedite rate",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Plan failure symptom",
    linkedOutcomeIds: [
      "mfg-outcome-lead-time",
      "mfg-outcome-utilisation",
      "mfg-outcome-margin",
    ],
  },
  {
    id: "mfg-kpi-dual-source-pct",
    label: "Critical parts dual-sourced/buffered",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Resilience coverage",
    linkedOutcomeIds: ["mfg-outcome-supply-resilience"],
  },
  {
    id: "mfg-kpi-supplier-otif",
    label: "Supplier OTIF",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Inbound reliability",
    linkedOutcomeIds: ["mfg-outcome-supply-resilience", "mfg-outcome-utilisation"],
  },
  {
    id: "mfg-kpi-recovery-days",
    label: "Disruption recovery time",
    unit: "days",
    polarity: "lower_better",
    executiveMeaning: "Resilience performance",
    linkedOutcomeIds: ["mfg-outcome-supply-resilience"],
  },
  {
    id: "mfg-kpi-contribution-margin",
    label: "Contribution margin",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Factory/product economic health",
    linkedOutcomeIds: ["mfg-outcome-margin"],
  },
  {
    id: "mfg-kpi-overtime-cost",
    label: "Overtime premium cost",
    unit: "currency",
    polarity: "lower_better",
    executiveMeaning: "Cost of fake capacity",
    linkedOutcomeIds: ["mfg-outcome-margin"],
  },
  {
    id: "mfg-kpi-discount-leakage",
    label: "Discount / clearance leakage",
    unit: "%",
    polarity: "lower_better",
    executiveMeaning: "Price discipline",
    linkedOutcomeIds: ["mfg-outcome-margin", "mfg-outcome-dealer"],
  },
  {
    id: "mfg-kpi-segment-share",
    label: "Priority segment share",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Strategic position",
    linkedOutcomeIds: ["mfg-outcome-share"],
  },
  {
    id: "mfg-kpi-strategic-win-rate",
    label: "Strategic bid win rate",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Quality of big-deal pursuit",
    linkedOutcomeIds: ["mfg-outcome-share"],
  },
  {
    id: "mfg-kpi-transformation-milestones",
    label: "Transformation milestone hit rate",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Future-fit execution",
    linkedOutcomeIds: ["mfg-outcome-future-fit"],
  },
  {
    id: "mfg-kpi-automation-roi",
    label: "Automation ROI vs plan",
    unit: "%",
    polarity: "higher_better",
    executiveMeaning: "Capex truth",
    linkedOutcomeIds: ["mfg-outcome-future-fit", "mfg-outcome-margin"],
  },
];
