import type { PackOntologyTerm } from "@/intelligence-packs/contract";

/** Phase 48 doc 02 — opaque pack vocabulary (never Core entity types). */
export const MANUFACTURING_ONTOLOGY: PackOntologyTerm[] = [
  {
    id: "mfg-term-factory",
    term: "Factory",
    definition: "Physical production site with constrained capacity",
    executiveMeaning: "Where build slots and utilisation live",
    aliases: ["Plant", "Site"],
    relatedOutcomeIds: [
      "mfg-outcome-utilisation",
      "mfg-outcome-margin",
      "mfg-outcome-lead-time",
    ],
  },
  {
    id: "mfg-term-line",
    term: "Line",
    definition: "Constrained production path inside a factory",
    executiveMeaning: "Bottleneck unit for scheduling",
    aliases: ["Workcentre"],
    relatedOutcomeIds: ["mfg-outcome-utilisation", "mfg-outcome-lead-time"],
  },
  {
    id: "mfg-term-model",
    term: "Model",
    definition: "Product family sold to market",
    executiveMeaning: "Strategic unit of mix and share",
    aliases: ["Platform"],
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-share",
      "mfg-outcome-margin",
    ],
  },
  {
    id: "mfg-term-variant",
    term: "Variant",
    definition: "Configurable expression of a model",
    executiveMeaning: "Complexity and inventory driver",
    aliases: ["Spec", "Configuration"],
    relatedOutcomeIds: [
      "mfg-outcome-inventory",
      "mfg-outcome-forecast",
      "mfg-outcome-margin",
    ],
  },
  {
    id: "mfg-term-dealer",
    term: "Dealer",
    definition: "Channel partner holding retail/inventory responsibility",
    executiveMeaning: "Demand and inventory proxy at the edge",
    aliases: ["Distributor", "Agent"],
    relatedOutcomeIds: [
      "mfg-outcome-dealer",
      "mfg-outcome-forecast",
      "mfg-outcome-working-capital",
    ],
  },
  {
    id: "mfg-term-region",
    term: "Region",
    definition: "Geographic demand aggregation",
    executiveMeaning: "Forecast and allocation unit",
    aliases: ["Territory", "Market"],
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-dealer",
      "mfg-outcome-share",
    ],
  },
  {
    id: "mfg-term-order-bank",
    term: "Order Bank",
    definition: "Firm and soft orders awaiting build",
    executiveMeaning: "Near-term demand truth vs plan",
    aliases: ["Backlog", "Order book"],
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-lead-time",
      "mfg-outcome-utilisation",
    ],
  },
  {
    id: "mfg-term-allocation",
    term: "Allocation",
    definition: "Rules assigning scarce product/slots to dealers/regions",
    executiveMeaning: "Political and commercial fairness surface",
    aliases: ["Allotment"],
    relatedOutcomeIds: [
      "mfg-outcome-dealer",
      "mfg-outcome-inventory",
      "mfg-outcome-share",
    ],
  },
  {
    id: "mfg-term-build-slot",
    term: "Build Slot",
    definition: "Discrete capacity reservation on a line/factory",
    executiveMeaning: "Scarce asset executives actually allocate",
    aliases: ["Slot", "Build week"],
    relatedOutcomeIds: [
      "mfg-outcome-utilisation",
      "mfg-outcome-lead-time",
      "mfg-outcome-dealer",
    ],
  },
  {
    id: "mfg-term-lead-time",
    term: "Lead Time",
    definition: "Promised or demonstrated time to fulfil",
    executiveMeaning: "Trust currency with dealers/customers",
    aliases: ["Promise date", "Cycle time"],
    relatedOutcomeIds: ["mfg-outcome-lead-time", "mfg-outcome-forecast"],
  },
  {
    id: "mfg-term-capacity-envelope",
    term: "Capacity Envelope",
    definition: "Demonstrated sustainable output band",
    executiveMeaning: "Truth vs sales ambition",
    aliases: ["Rated capacity"],
    relatedOutcomeIds: ["mfg-outcome-utilisation", "mfg-outcome-forecast"],
  },
  {
    id: "mfg-term-inventory",
    term: "Inventory",
    definition: "Finished goods, WIP, and parts held",
    executiveMeaning: "Cash and service trade-off",
    aliases: ["Stock"],
    relatedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-working-capital"],
  },
  {
    id: "mfg-term-safety-stock",
    term: "Safety Stock",
    definition: "Intentional buffer against uncertainty",
    executiveMeaning: "Insurance with a cost",
    aliases: ["Buffer"],
    relatedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-supply-resilience"],
  },
  {
    id: "mfg-term-wip",
    term: "WIP",
    definition: "Work-in-process inside factories",
    executiveMeaning: "Hidden cash and flow friction",
    aliases: ["In-process"],
    relatedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-utilisation"],
  },
  {
    id: "mfg-term-supplier",
    term: "Supplier",
    definition: "External provider of parts/materials",
    executiveMeaning: "Resilience and OTIF source",
    aliases: ["Vendor"],
    relatedOutcomeIds: ["mfg-outcome-supply-resilience", "mfg-outcome-margin"],
  },
  {
    id: "mfg-term-part",
    term: "Part",
    definition: "Component required to build",
    executiveMeaning: "BOM-level constraint",
    aliases: ["Component", "SKU"],
    relatedOutcomeIds: ["mfg-outcome-supply-resilience", "mfg-outcome-inventory"],
  },
  {
    id: "mfg-term-commodity",
    term: "Commodity",
    definition: "Input whose price/availability swings externally",
    executiveMeaning: "Margin and forecast risk",
    aliases: ["Raw material"],
    relatedOutcomeIds: [
      "mfg-outcome-margin",
      "mfg-outcome-forecast",
      "mfg-outcome-working-capital",
    ],
  },
  {
    id: "mfg-term-construction",
    term: "Construction Activity",
    definition: "Downstream building/infra demand signal",
    executiveMeaning: "Leading indicator for dealer demand",
    aliases: ["Housing starts", "Project pipeline"],
    relatedOutcomeIds: [
      "mfg-outcome-forecast",
      "mfg-outcome-dealer",
      "mfg-outcome-share",
    ],
  },
  {
    id: "mfg-term-working-capital",
    term: "Working Capital",
    definition: "Inventory + receivables − payables",
    executiveMeaning: "Cash trapped in the operating cycle",
    aliases: ["CCC"],
    relatedOutcomeIds: ["mfg-outcome-working-capital"],
  },
  {
    id: "mfg-term-frozen-window",
    term: "Frozen Window",
    definition: "Schedule period closed to casual change",
    executiveMeaning: "Discipline boundary for plan stability",
    aliases: ["Firm zone"],
    relatedOutcomeIds: ["mfg-outcome-forecast", "mfg-outcome-utilisation"],
  },
  {
    id: "mfg-term-mix",
    term: "Mix",
    definition: "Proportion of models/variants built and sold",
    executiveMeaning: "Margin and capacity shape",
    aliases: ["Product mix"],
    relatedOutcomeIds: [
      "mfg-outcome-margin",
      "mfg-outcome-utilisation",
      "mfg-outcome-share",
    ],
  },
  {
    id: "mfg-term-expedite",
    term: "Expedite",
    definition: "Out-of-sequence acceleration of an order",
    executiveMeaning: "Symptom of plan failure",
    aliases: ["Hot order"],
    relatedOutcomeIds: [
      "mfg-outcome-lead-time",
      "mfg-outcome-margin",
      "mfg-outcome-utilisation",
    ],
  },
  {
    id: "mfg-term-eo",
    term: "E&O",
    definition: "Excess and obsolete inventory",
    executiveMeaning: "Capital destruction signal",
    aliases: ["Dead stock"],
    relatedOutcomeIds: ["mfg-outcome-inventory", "mfg-outcome-working-capital"],
  },
  {
    id: "mfg-term-oee",
    term: "OEE",
    definition: "Overall equipment effectiveness",
    executiveMeaning: "Quality of capacity use",
    relatedOutcomeIds: ["mfg-outcome-utilisation"],
  },
  {
    id: "mfg-term-electrification",
    term: "Electrification",
    definition: "Shift of product/process toward electric platforms",
    executiveMeaning: "Strategic posture bet",
    aliases: ["EV transition"],
    relatedOutcomeIds: ["mfg-outcome-future-fit", "mfg-outcome-share"],
  },
  {
    id: "mfg-term-automation",
    term: "Automation",
    definition: "Capex/process investment reducing labour dependency",
    executiveMeaning: "Productivity and resilience bet",
    aliases: ["Robotics", "Lights-out"],
    relatedOutcomeIds: [
      "mfg-outcome-future-fit",
      "mfg-outcome-utilisation",
      "mfg-outcome-margin",
    ],
  },
];

/** Terms that must never appear as Core entity type names. */
export const MANUFACTURING_FORBIDDEN_CORE_TYPES = [
  "Factory",
  "BuildSlot",
  "OrderBank",
  "Dealer",
  "Variant",
] as const;
